### ISSUE TITLE
parse

### ISSUE THREAD

**Issue by gpffh20** [minivell/minivell#48]
에러처리 내용

**Comment by gpffh20** [comment]
<img width="135" alt="Screenshot 2024-01-13 at 23 11 55" src="https://github.com/minivell/minivell/assets/111725249/918600d8-c9a4-40ae-ad2c-2343422d0868">

<img width="180" alt="Screenshot 2024-01-13 at 23 11 48" src="https://github.com/minivell/minivell/assets/111725249/bbe36b87-b658-4b99-aaa2-af5de2cf81d6">


무한 루프 발생

**Comment by gykoh42** [comment]
syntax error로 처리 완료!
